### ISSUE TITLE
NullPointer for the non mandatory attributes

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigee/apigee-registry-maven-plugin#5]
************************************************************************
API Deployment
************************************************************************
null
java.lang.NullPointerException
        at com.google.cloud.apigeeregistry.v1.ApiDeployment$Builder.setEndpointUri(ApiDeployment.java:2966)
        at com.apigee.registry.config.utils.ApigeeRegistryClient.updateAPIDeployment(ApigeeRegistryClient.java:368)
        at com.apigee.registry.config.mavenplugin.APIDeploymentMojo.doUpsert(APIDeploymentMojo.java:169)
        at com.apigee.registry.config.mavenplugin.APIDeploymentMojo.execute(APIDeploymentMojo.java:133)

**Comment by ssvaidyanathan** [comment]
v1.0.2
